#!/bin/sh
#PBS -j oe
#PBS -l nodes=1:ppn=1:xk
#PBS -l walltime=48:00:00
#PBS -q low
#PBS -N Your_Jobs_Name
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out


cd $PBS_O_WORKDIR

module load cudatoolkit/7.5.18-1.0502.10743.2.1
module load craype-accel-nvidia52
module load python/0.3.0


aprun -n 1 -N 1 ./genga
